### ISSUE TITLE
Request to document windows and macos-latest-xlarge

### ISSUE THREAD

**Issue by pamelafox** [pgvector/setup-pgvector#2]
It's so helpful that you've documented workflows for ubuntu and mac runners. 
Could you also add the windows and M1 runners? Here's a workflow where I use them:
https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/.github/workflows/app-tests.yaml
But those don't necessarily follow best practices, so I'm trying to adjust them to match your recommendations here.

Thanks!

**Comment by pamelafox** [comment]
Update: It looks like your recommendation for mac-13 also works for the M1 runner (macos-latest-xlarge). I haven't got my Windows setup working with the latest version of pgvector for some reason, it doesn't think pgvector is installed, so I'd love to see that documented.

**Comment by ankane** [comment]
Hi @pamelafox, added Windows instructions in the commit above.

**Comment by pamelafox** [comment]
Thanks for that, my workflow works across a matrix of many OSes now:
https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/.github/workflows/app-tests.yaml
